# Generated by Django 4.2.7 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_make_mobile_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessibility_mode',
            field=models.BooleanField(default=False, help_text='Enable accessibility features like screen reader support'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast_mode',
            field=models.BooleanField(default=False, help_text='Enable high contrast visual theme'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi - हिन्दी'), ('bn', 'Bengali - বাংলা'), ('te', 'Telugu - తెలుగు'), ('mr', 'Marathi - मराठी'), ('ta', 'Tamil - தமிழ்'), ('gu', 'Gujarati - ગુજરાતી'), ('kn', 'Kannada - ಕನ್ನಡ'), ('ml', 'Malayalam - മലയാളം'), ('pa', 'Punjabi - ਪੰਜਾਬੀ'), ('or', 'Odia - ଓଡ଼ିଆ'), ('as', 'Assamese - অসমীয়া')], default='en', help_text='Primary language preference (same as language, for backward compatibility)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='text_size_preference',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', help_text='Preferred text size', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_language_preference',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi - हिन्दी'), ('bn', 'Bengali - বাংলা'), ('te', 'Telugu - తెలుగు'), ('mr', 'Marathi - मराठी'), ('ta', 'Tamil - தமிழ்'), ('gu', 'Gujarati - ગુજરાતી'), ('kn', 'Kannada - ಕನ್ನಡ'), ('ml', 'Malayalam - മലയാളം'), ('pa', 'Punjabi - ਪੰਜਾਬੀ'), ('or', 'Odia - ଓଡ଼ିଆ'), ('as', 'Assamese - অসমীয়া')], default='en', help_text='Preferred language for voice input/output', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi - हिन्दी'), ('bn', 'Bengali - বাংলা'), ('te', 'Telugu - తెలుగు'), ('mr', 'Marathi - मराठी'), ('ta', 'Tamil - தமிழ்'), ('gu', 'Gujarati - ગુજરાતી'), ('kn', 'Kannada - ಕನ್ನಡ'), ('ml', 'Malayalam - മലയാളം'), ('pa', 'Punjabi - ਪੰਜਾਬੀ'), ('or', 'Odia - ଓଡ଼ିଆ'), ('as', 'Assamese - অসমীয়া')], default='en', help_text='Preferred language for UI and communications', max_length=10),
        ),
    ]
