# Generated by Django 4.2.4 on 2025-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0002_mlmodel_config_path_mlmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='supported_languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
