# Generated by Django 4.2.7 on 2025-11-08 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0008_complaint_audio_language_detected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_complaints', models.IntegerField(default=0)),
                ('new_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('rejected_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('high_priority_count', models.IntegerField(default=0)),
                ('medium_priority_count', models.IntegerField(default=0)),
                ('low_priority_count', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(blank=True, null=True)),
                ('avg_resolution_time_hours', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('total_complaints', models.IntegerField(default=0)),
                ('open_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('avg_api_response_time_ms', models.FloatField(blank=True, null=True)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('failed_api_calls', models.IntegerField(default=0)),
                ('database_size_mb', models.FloatField(blank=True, null=True)),
                ('media_storage_mb', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('complaint_created', 'Complaint Created'), ('complaint_viewed', 'Complaint Viewed'), ('complaint_updated', 'Complaint Updated'), ('chat_message', 'Chat Message'), ('profile_updated', 'Profile Updated'), ('search', 'Search'), ('page_view', 'Page View')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_39836b_idx'), models.Index(fields=['activity_type', '-created_at'], name='analytics_u_activit_7e1dbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('rejected_complaints', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(blank=True, null=True)),
                ('avg_resolution_time_hours', models.FloatField(blank=True, null=True)),
                ('resolution_rate', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('total_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='complaints.department')),
            ],
            options={
                'verbose_name_plural': 'Department Metrics',
                'ordering': ['-date', 'department'],
                'unique_together': {('department', 'date')},
            },
        ),
    ]
