# Generated by Django 4.2.7 on 2025-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_area_type_complaint_gps_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
