# Generated by Django 4.2.7 on 2025-10-06 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0003_alter_complaint_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI processing confidence score'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_processed_text',
            field=models.TextField(blank=True, help_text='AI enhanced/processed complaint text'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio complaint file', null=True, upload_to='complaints/audio/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='audio_transcription',
            field=models.TextField(blank=True, help_text='Transcribed text from audio/video'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_classification',
            field=models.JSONField(blank=True, default=dict, help_text='AI department classification results'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='detected_objects',
            field=models.JSONField(blank=True, default=list, help_text='Objects detected in images/video'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Image complaint file', null=True, upload_to='complaints/images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_ocr_text',
            field=models.TextField(blank=True, help_text='Text extracted from images via OCR'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, help_text='Location description or address', max_length=500),
        ),
        migrations.AddField(
            model_name='complaint',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Video multimodal analysis results'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video complaint file', null=True, upload_to='complaints/videos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaints.department'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sentiment',
            field=models.FloatField(help_text='Sentiment analysis score', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complaintcategory'),
        ),
    ]
