# Generated by Django 4.2.7 on 2025-10-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_escalation_fields'),
        ('complaints', '0004_complaintcategory_alter_complaint_options_and_more'),
    ]

    operations = [
    ]
