# Generated by Django 4.2.7 on 2025-11-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_video_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='escalated',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='escalation_date',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes and escalation history'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When the complaint was last escalated', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='escalation_count',
            field=models.IntegerField(default=0, help_text='Number of times this complaint has been escalated'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes for tracking'),
        ),
    ]
