# Generated by Django 4.2.7 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaint_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='audio_language_detected',
            field=models.CharField(blank=True, help_text='Language detected in audio transcription', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='auto_translated',
            field=models.BooleanField(default=False, help_text='Whether the complaint was automatically translated'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='original_text',
            field=models.TextField(blank=True, help_text='Original complaint text before translation (if submitted in non-English)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('or', 'Odia'), ('as', 'Assamese')], default='en', help_text='Language in which the complaint was originally submitted', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translated_text',
            field=models.TextField(blank=True, help_text='English translation of the complaint for AI processing'),
        ),
    ]
