# Generated by Django 4.2.7 on 2025-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_audio_language_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, help_text='Unique complaint identifier: BC-YEAR-CITY-DEPT-SEQUENCE', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gemini_raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Gemini API response including department classification, confidence scores, and metadata'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submitted_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('or', 'Odia'), ('as', 'Assamese')], default='en', help_text='Language in which the complaint was originally submitted', max_length=10),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_number'], name='complaints__complai_998a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='complaints__status_39c2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['department', 'status'], name='complaints__departm_77b491_idx'),
        ),
    ]
