# Generated by Django 4.2.7 on 2025-11-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_complaint_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Open Location Code (Plus Code) for precise location (e.g., 7JWWJ6J9+2V)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward_id',
            field=models.CharField(blank=True, help_text='Assigned ward/zone identifier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward_name',
            field=models.CharField(blank=True, help_text='Ward/zone name for the complaint location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location_method',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual Entry'), ('address', 'Address Lookup'), ('plus_code', 'Plus Code')], default='gps', max_length=50),
        ),
    ]
