# Generated by Django 4.2.7 on 2025-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_add_mapmyindia_plus_code_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the complaint was resolved', null=True),
        ),
    ]
