# Generated by Django 4.2.7 on 2025-11-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_department_options_department_api_endpoint_and_more'),
    ]

    operations = [
    ]
