# Generated by Django 4.2.7 on 2025-11-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_quickreplytemplate_chatlog_escalated_to_human_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='reply_metadata',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='quickreplytemplate',
            name='buttons',
        ),
        migrations.CreateModel(
            name='ReplyMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply_metadata', to='chatbot.chatlog')),
            ],
        ),
        migrations.CreateModel(
            name='QuickReplyButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='chatbot.quickreplytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='chatbot.chatnotification')),
            ],
        ),
    ]
