# Generated by Django 4.2.7 on 2025-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatlog_reply_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
